sudo: required
language: python
cache: pip

services: 
  - docker

python:
  - "3.6"


install:
  - distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
  - curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
  - curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
  - sudo apt-get update && sudo apt-get install -y nvidia-container-toolkit
  - sudo systemctl restart docker

script:
  - docker run --gpus all nvidia/cuda:9.0-base nvidia-smi
